### ISSUE TITLE
Allow for deletion of vault credentials for MinioUsers

### ISSUE THREAD

**Issue by bdomars** [Walkbase/minio-resources-operator#6]

**Comment by jabbors** [comment]
Could be implemented in the CRD with an annotation. If the annotation is set to a specific value it will be deleted, other the entry is left in vault.

Eg.

```
apiVersion: minio.walkbase.com/v1
kind: MinioUser
metadata:
  name: username
  namespace: minio-resources-operator-system
  annotations:
    delete-vault-entry: true # Only if this key has value true -> delete
```
